/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author psucoder
 */

#include <bits/stdc++.h>


using namespace std;

vector<int> readArrayInt(istream &in, unsigned long n) {
    vector<int> ar(static_cast<unsigned long>(n));
    for (int i = 0; i < n; ++i) in >> ar[i];
    return ar;
}

using namespace std;

class TaskA {
public:
    void solve(std::istream &in, std::ostream &out) {
        unsigned long n, k;
        in >> n >> k;
        auto a = readArrayInt(in, n);
        sort(a.begin(), a.end(), greater<>());
        for (int i = 0; i < n; ++i) {
            if (k % a[i] == 0) {
                out << k / a[i] << endl;
                break;
            }
        }
    }
};


int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    TaskA solver;
    std::istream &in(std::cin);
    std::ostream &out(std::cout);
    solver.solve(in, out);
    return 0;
}
